name: Generate language bar charts

on: workflow_dispatch

jobs:
  GenerateChart:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate bar charts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LANG_TO_EXCLUDE: ${{ vars.LANG_TO_EXCLUDE }}
          LANG_NAME_MAP: ${{ vars.LANG_NAME_MAP }}
        run: |
          python ./main.py
      - name: Stash created charts
        run: |
          ls
          git stash
      - name: Checkout to charts branch
        uses: actions/checkout@v4
        with:
          ref: BarCharts
      - name: Stash pop
        run: |
          git stash pop
          ls
      - name: Commit and Push charts
        run: |
          git add Dark.png
          git add Light.png
          git commit -m "Update bar charts"
