name: Generate language bar charts

on: workflow_dispatch

permissions:
  contents: write

jobs:
  GenerateChart:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate bar charts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LANG_TO_EXCLUDE: ${{ vars.LANG_TO_EXCLUDE }}
          LANG_NAME_MAP: ${{ vars.LANG_NAME_MAP }}
        run: |
          python ./main.py
      - name: Checkout to charts branch
        run: |
          git fetch origin
          git checkout BarCharts
      - name: Copy charts from tmp dir
        run: |
          cp /tmp/Top_Used_Languages-light.png ./.
          cp /tmp/Top_Used_Languages-dark.png ./.
      - name: Commit and Push charts
        run: |
          git add Top_Used_Languages-light.png Top_Used_Languages-dark.png
          git commit -m "Update bar charts on ${{ github.event_name }} - ${{ github.run_number }} ($(date '+%F %H:%M:%S'))"
          git push
