name: Language bar charts

on: 
  workflow_dispatch:
  schedule:
   - cron: 0 0 * * *

permissions:
  contents: write

env:
  commit_msg: 'Update bar charts on ${{ github.event_name }} - action run ${{ github.run_number }}'
  dest_branch_name: 'BarCharts'
  l_theme_filename: 'Top_Used_Languages-light.png'
  d_theme_filename: 'Top_Used_Languages-dark.png'

jobs:
  GenerateChart:
    runs-on: ${{ vars.SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate bar charts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LANG_TO_EXCLUDE: ${{ vars.LANG_TO_EXCLUDE }}
          LANG_NAME_MAP: ${{ vars.LANG_NAME_MAP }}
        run: |
          python ./main.py

      - name: Checkout to charts branch
        run: |
          git fetch origin
          git checkout ${{ env.dest_branch_name }}

      - name: Copy charts from tmp dir
        run: |
          cp /tmp/${{ env.l_theme_filename }} ./. && rm /tmp/${{ env.l_theme_filename }}
          cp /tmp/${{ env.d_theme_filename }} ./. && rm /tmp/${{ env.d_theme_filename }}

      - name: Check if there are any changes
        id: diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and Push charts
        if: steps.diff.outputs.changed == 'true'
        run: |
          git add ${{ env.l_theme_filename }} ${{ env.d_theme_filename }}
          git commit -m "${{ env.commit_msg }} ($(date '+%F %H:%M:%S'))"
          git push
